# Feature Branch PR Description
# Only generates descriptions for PRs targeting specific branches

name: Describe Feature PRs
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - develop
      - release/*

jobs:
  describe:
    # Only run for PRs from feature branches
    if: startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'feat/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate PR Description
        uses: augmentcode/describe-pr@v0
        with:
          augment_session_auth: ${{ secrets.AUGMENT_SESSION_AUTH }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ github.event.pull_request.number }}
          repo_name: ${{ github.repository }}

      - name: Add feature label
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['feature', 'auto-described']
            })
